# Generated by Django 4.2.3 on 2023-08-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text360', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created_at',)},
        ),
    ]
